app:
  name: ui
  image:
    repository: 'onecx/onecx-announcement-ui'
  routing:
    enabled: true
    path: /mfe/announcement/
  
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: "./OneCXAnnouncementModule"
          description: "OneCX Announcement UI"
          note: "OneCX Announcement UI auto import via MF operator"
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-announcement
          tagName: ocx-announcement-component
        announcement-banner:
          exposedModule: "./OneCXAnnouncementBannerComponent"
          description: "Announcement banner component"
          type: COMPONENT
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-announcement
          tagName: ocx-announcement-banner-component
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          ANNOUNCEMENT:
            CREATE: Create announcement
            DELETE: Delete announcement
            EDIT: Edit announcement
            SEARCH: Search announcement
            VIEW: View announcement
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-announcement-ui"
            
# PIPE Config
